apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: homework-deployment
  labels:
    app: homework
spec:
  selector:
    matchLabels:
      app: homework
  replicas: 1
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: local/homework-service
        imagePullPolicy: Always
        ports:
        - name: homework
          containerPort: 50052

---

apiVersion: v1
kind: Service
metadata:
  name: homework
spec:
  selector:
    app: homework
  ports:
  - port: 50052
    targetPort: homework

---

apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: homework
data:
  port: 50052

---

apiVersion: v1
kind: Ingress
metadata:
  name: homework-ingress
  namespace: default
spec:
  rules:
  - host: homework.roomone.com
    http:
      paths:
      - backend:
          serviceName: homework
          servicePort: 50052

---

apiVersion: v1
kind: StatefulSet
metadata:
  name: homework
spec:
  serviceName: "homework"
  replicas: 2
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: localhost/homework
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 50052
  podManagementPolicy: "Parallel"